[package]
org = "ballerinax"
name = "persist.inmemory"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["persist", "inmemory"]
repository = "https://github.com/ballerina-platform/module-ballerinax-persist.inmemory"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "@toml.version@"
path = "../native/build/libs/persist.inmemory-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "@persist.version@"
path = "./lib/persist-native-@persist.native.version@.jar"
