[package]
org = "ballerinax"
name = "persist.inmemory"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["persist", "inmemory"]
repository = "https://github.com/ballerina-platform/module-ballerinax-persist.inmemory"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.3.0"
path = "../native/build/libs/persist.inmemory-native-1.3.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "1.3.0"
path = "./lib/persist-native-1.3.0-20240404-142400-65c3633.jar"
